spring:
  application:
    name: Amang_timetable
  h2:
    console:
      enabled: true   # ? ?? ??
      path: /h2-console   # ?? ?? (?? /h2-console)
  datasource:
    url: jdbc:h2:mem:testdb   # in-memory DB (??)
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
