spring:
  application:
    name: Amang_timetable

  datasource:
    url: jdbc:mysql://localhost:3306/amang_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wjdgh01!!

  jpa:
    hibernate:
      ddl-auto: update   # (create, create-drop, update, validate 중 선택)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
